version: '3'

services: 
    nginx:
        image: nginx:1.13
        volumes: 
            - "./app:/var/www/html"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
        ports:
            - "80:80"
        depends_on:
            - web

    web:
        image: php:7.4-fpm
        volumes: 
            - "./app:/var/www/html"
        ports: 
            - "3000:3000"

    ocr:
        image: guilhermeadc/ocr-server
        volumes: 
            - /script/tmp:/var/ocr-server/.
